require("nevio.plugins-setup")
require("nevio.core.options")
require("nevio.core.keymaps")
require("nevio.core.colorscheme")
require("nevio.plugins.comment")
require("nevio.plugins.nvim-tree")
require("nevio.plugins.lualine")
require("nevio.plugins.telescope")
require("nevio.plugins.nvim-cmp")
require("nevio.plugins.lsp.mason")
require("nevio.plugins.lsp.lspconfig")
--[[ require("nevio.plugins.lsp.lspsaga") ]]
require("nevio.plugins.lsp.null-ls")
require("nevio.plugins.autopairs")
require("nevio.plugins.treesitter")
require("nevio.plugins.gitsigns")
